namespace: jenkins
name: jenkinshelm
image: jfrog.it-academy.by/public/jenkins-ci:pkostenko


nfs_path_sa: /mnt/IT-Academy/nfs-data/sa2-22-22/pkostenko/jenkins
nfs_server_sa: 192.168.37.105

basic_security: /var/jenkins_home/init.groovy.d/basic-security.groovy
jenkins_yaml: /var/jenkins_home/casc_configs/jenkins.yaml
jenkins_config: /var/jenkins_home
email: pasha.167988@yandex.by


ingress:
  enabled: enabled
host: jenkins.k8s-12.sa
ingress_port: 8080
main_host_url: http://jenkins.k8s-12.sa/

resources:
  requests:
    cpu: 2000m
    memory: 2000Mi
  limits:
    cpu: 3000m
    memory: 2500Mi  


master_port: 8080
master_targetport: 8080
slave_port: 50000
slave_targetport: 50000 

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 751~
